### ISSUE TITLE
Azure DevOps authentication failing

### ISSUE THREAD

**Issue by smholvoet** [lluchmk/semantic-release-ado#10]
How exactly should I authenticate to my Azure DevOps repo?

Currently running into the following error:

```log
[4:22:40 PM] [semantic-release] › ℹ  Running semantic-release version 17.1.1
[4:22:40 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/changelog"
[4:22:40 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/github"
[4:22:40 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/git"
[4:22:40 PM] [semantic-release] › ✔  Loaded plugin "analyzeCommits" from "@semantic-release/commit-analyzer"
[4:22:40 PM] [semantic-release] › ✔  Loaded plugin "analyzeCommits" from "semantic-release-ado"
[4:22:40 PM] [semantic-release] › ✔  Loaded plugin "generateNotes" from "@semantic-release/release-notes-generator"
[4:22:40 PM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/changelog"
[4:22:40 PM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/git"
[4:22:40 PM] [semantic-release] › ✔  Loaded plugin "prepare" from "semantic-release-ado"
[4:22:40 PM] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/github"
[4:22:40 PM] [semantic-release] › ✔  Loaded plugin "addChannel" from "@semantic-release/github"
[4:22:40 PM] [semantic-release] › ✔  Loaded plugin "success" from "@semantic-release/github"
[4:22:40 PM] [semantic-release] › ✔  Loaded plugin "fail" from "@semantic-release/github"
[4:22:40 PM] [semantic-release] › ✖  An error occurred while running semantic-release: Error: Command failed with exit code 128: git ls-remote --heads https://[secure]@dev.azure.com/<orgName>/Versioning/_git/Versioning
fatal: Authentication failed for 'https://dev.azure.com/<orgName>/Versioning/_git/Versioning/'

```

My pipeline:

```yaml
trigger: none

jobs:
- job: Build
  pool:
    vmImage: 'ubuntu-latest'
  steps:

  - script: >
        npx -p semantic-release
        -p @semantic-release/changelog
        -p @semantic-release/git
        -p semantic-release-ado
        semantic-release
    env: { GH_TOKEN: $(GitHubToken) }
    displayName: 'Semantic release'

  - script: echo $(nextRelease)
    displayName: 'Show next version'
```

I'm guessing the `GH_TOKEN` environment variable is wrong, as I'm trying to authenticate to AzDo, not GitHub?
