### ISSUE TITLE
The build number format $(nextRelease)" contains invalid character

### ISSUE THREAD

**Issue by PrettySolution** [lluchmk/semantic-release-ado#22]
Hello, can't get remantic-release-ado working with the latest semantic-release library.
It fails with an error `##[error]TF209010`
LOG:
```
[8:42:42 PM] [semantic-release] › ✔  Published release 1.2.2 on default channel
Async Command Start: Update Build Number
Async Command End: Update Build Number
##[error]TF209010: The build number format $(nextRelease)" contains invalid character(s), is too long, or ends with '.'. The maximum length of a build number is 255 characters. Characters which are not allowed include '"', '/', ':', '<', '>', '\', '|', '?', '@', and '*'.
Finishing: Release
```

Here is my pipeline:
```
  - bash: |
      npm install -g semantic-release @semantic-release/exec semantic-release-plus @semantic-release-plus/docker semantic-release-ado
      semantic-release
    displayName: 'Release'
    env:
      GITHUB_TOKEN: $(GH_TOKEN)
      DOCKER_REPOSITORY_NAME: $(DOCKER_REPOSITORY_NAME)
      DOCKER_REPOSITORY: $(AWS_ACCOUNT_ID).dkr.ecr.$(AWS_REGION).amazonaws.com/$(DOCKER_REPOSITORY_NAME)
```

Please, help!
