### ISSUE TITLE
Variable $(nextRelease) is not set in the same ado script context

### ISSUE THREAD

**Issue by piejanssens** [lluchmk/semantic-release-ado#23]
```
  - script: |
      npx \
      -p semantic-release-yaml \
      -p semantic-release-ado \
      -p @semantic-release/changelog \
      semantic-release
      contents="$(jq '.version = "$(nextRelease)"' package.json)" && \
      echo -E "${contents}" > package.json
````

The above example doesn't work. I have to put the last two lines in a separate pipeline script in order to get a value inside the variable `nextRelease`.

**Comment by lluchmk** [comment]
Hey there, sorry for the super late response.

Yes, that works as expected, because the plugin is just setting the semantic-release version as a variable, and as described in the [Pipelines documentation](https://learn.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#set-variables-in-scripts) a variable cannot be used in the step that defines it.

Hope this helps,
Closing the issue for now, feel free to reopen if we can add anything else.

**Comment by crush83** [comment]
This issue doesn't need to be reopened, but I wanted to add to the conversation incase someone else finds themselves here. My issue was not with the plugin, but just not quite understanding how pipeline variables work in Azure DevOps. I read the pipelines documentation mentioned above by @lluchmk and came to an incorrect conclusion:

> To set a variable from a script, you use the task.setvariable logging command This updates the environment variables for subsequent jobs. Subsequent jobs have access to the new variable with macro syntax and in _**tasks as environment variables**_.

I was trying to access the `nextRelease` variable in the subsequent step using the macro syntax `$(nextRelease)` but it wasn't available. Then, I tried the environment variable syntax `$env:nextRelease` and it still didn't work. I eventually found my answer in the same document, but a different section called [Use output variables from tasks](https://learn.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#use-output-variables-from-tasks). My confusion was thinking that the variable was not an output variable because `isOutput` was not set to true.

> To reference a variable from a different task within the same job, use TASK.VARIABLE.

I had to set a name on my semantic release task in order to access the variable within the same job:

```yaml
          - task: Npm@1
            displayName: Semantic Release
            name: SemanticRelease
            env:
              GIT_CREDENTIALS: $(System.AccessToken)
              CI_COMMIT_BRANCH: $(Build.SourceBranchName)
            inputs:
              command: custom
              verbose: false
              workingDir: $(PROJECT_DIR)
              customCommand: run ci:release
```
> Note: `ci:release` is just an npm script in our package.json for `semantic-release`...

I was then able to access the `nextRelease` variable in the next step as follows:

```yaml
          - task: PowerShell@2
            displayName: 'Update Build Number'
            inputs:
              targetType: 'inline'
              script: |
                Write-Host "##vso[build.updatebuildnumber]$(SemanticRelease.nextRelease)"
```

Hope this helps someone.


*EDIT*
I'm still a little confused on why I was unable to access the variable with macro syntax. I originally didn't have a `name` set on the `task` for semantic release, and `isoutput` was being set to false by the plugin.

The [documentation](https://learn.microsoft.com/en-us/azure/devops/pipelines/process/set-variables-scripts?view=azure-devops&tabs=powershell#levels-of-output-variables) is worded in a way that is a bit confusing when it comes to task.setvariable and the isoutput setting.

> - Output variables set in the same job without the isoutput parameter. To reference these variables, you'll use macro syntax. Example: $(myVar).
> - Output variables set in the same job with the isoutput parameter. To reference these variables, you'll include the task name. Example: $(myTask.myVar).

My thought here is that explicitly setting the `isOutput`, even to false, falls under the second use case above. I'm thinking this would fall under "with the isoutput parameter"
> ##vso[task.setvariable variable=myOutputJobVar;isoutput=false]

and that is what the plugin does. The plugin could potentially be modified to omit the `isoutput=false` if this is indeed the case. If it's not the case, then I'm still misunderstanding something here...
