### ISSUE TITLE
EINVALIDGHTOKEN Invalid GitHub token

### ISSUE THREAD

**Issue by coopernicholas** [lluchmk/semantic-release-ado#28]
I can not seem to get my yaml file to authenticate with my local DevOps server. Below is my YAML file. Any help would be appreciated! 

```
trigger:
- main

variables:
  buildOutputFolder: 'dist'

pool:
  name: default

steps:

- checkout: self
  persistCredentials: true

- script: |
    npm install
  displayName: 'npm install'

- script: 
      npx -p semantic-release
      -p @semantic-release/git
      -p semantic-release-ado
      semantic-release --debug
  env: { GH_TOKEN: $(GitHubToken) }
  displayName: 'Semantic release'
    
- task: Npm@1
  displayName: 'npm build'
  inputs:
    command: custom
    verbose: false
    customCommand: 'run build'

- task: CopyFiles@2
  inputs:
    sourceFolder: "$(buildOutputFolder)"
    contents: '**/*' 
    targetFolder: '$(Build.ArtifactStagingDirectory)'
      
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'build'
    publishLocation: 'Container'
```
